version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - node node_modules/webpack/bin/webpack.js --config ./webpack-production.config.js --progress --colors
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files: 
    - '**/*'
