version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - webpack --config ./webpack-production.config.js --progress --colors
  post_build:
    commands:
      - echo Build completed on `date`
