version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - node node_modules/webpack/bin/webpack.js --config ./webpack-production.config.js --progress --colors
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir .build
      - tar cvzf .build/blogapp.tar.gz src server node_modules *.*
artifacts:
  files: 
    - .build/blogapp.tar.gz
